// Generated by CoffeeScript 1.9.2
(function() {
  describe("The graph proxy", function() {
    it("is a function of jas.Editor", function() {
      return expect(typeof jas.Editor.proxy).toBe('function');
    });
    it("which returns an object", function() {
      var graph;
      graph = jas.Editor.proxy();
      return expect(typeof graph).toBe('object');
    });
    return describe("One graph doesn't influent another", function() {
      var a, b, graph1, graph2;
      graph1 = jas.Editor.proxy();
      graph2 = jas.Editor.proxy();
      a = {};
      b = {};
      graph1.node.add(a);
      graph1.node.add(b);
      graph1.edge.add({
        source: a,
        target: b
      });
      return it("When nodes and edges added to one graph, the another one remains unchanged", function() {
        expect(graph1.node.data.length).toBe(2);
        expect(graph1.edge.data.length).toBe(1);
        expect(graph2.node.data.length).toBe(0);
        return expect(graph2.edge.data.length).toBe(0);
      });
    });
  });

}).call(this);
